services:
  server-php:
    build:
      context: ./server-php
      target: development
    ports:
      - 9000:80
    networks:
      - appnet
  server-node:
    build:
      context: ./server-node
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - appnet
  app:
    build:
      context: ./app
    ports:
      - 4000:4000
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
